input_dir: /mnt/c/Users/Landon/root_gnn/processed/v1
evts_per_file: 1000
output_dir: /mnt/c/Users/Landon/root_gnn/
model: GlobalClassifier
loss_name: GlobalLoss
loss_pars: 1, 1

batch_size: 100
num_iters: 1 
learning_rate: 0.0005
num_epochs: 100
stop_on: "auc"
patiences: 20
log_freq: 10
val_batches: 100
shuffle_size: 1000
dropout_rate: 0.0
encoder_size: [64,64]
core_size: [64,64]
