#!/usr/bin/env python


if __name__ =="__main__":
    import argparse
    from root_gnn import utils
    import matplotlib.pyplot as plt

    parser = argparse.ArgumentParser(description='View training info as function of time')
    add_arg = parser.add_argument
    add_arg('log_file',  help="log file")
    add_arg('outname',  help="output file name")
    add_arg('-t', '--time',  type=int, help="which time frame", default=0)

    args = parser.parse_args()

    file_name = args.log_file
    outname = args.outname
    itime = args.time

    df, time_list = utils.read_log(file_name)

    fig, axs = plt.subplots(2, 2, figsize=(12, 10), constrained_layout=True)
    axs = axs.flatten()

    utils.plot_log(df[itime], "default", axs=axs)
    name = "Training info as function of time"
    fig.suptitle(name, fontsize=16)

    plt.savefig(outname)
